import React, { useMemo } from "react";
import { format } from "date-fns";
import { useAppStore, type AppState } from "@/store/useAppStore";
import { generateInsights } from "@/utils/insightEngine";

export function StudyReport() {
  const sessions = useAppStore((state: AppState) => state.sessions);
  const subjects = useAppStore((state: AppState) => state.subjects);
  const totalXP = useAppStore((state: AppState) => state.totalXP);
  const level = useAppStore((state: AppState) => state.level);
  const rank = useAppStore((state: AppState) => state.rank);

  const stats = useMemo(() => {
    const totalSeconds = sessions.reduce((acc, s) => acc + s.actualSeconds, 0);
    const totalHours = (totalSeconds / 3600).toFixed(1);
    const sessionCount = sessions.length;
    const insights = generateInsights(sessions, subjects);
    
    return { totalHours, sessionCount, insights };
  }, [sessions, subjects]);

  return (
    <div id="print-report" className="hidden print:block bg-white text-slate-900 p-12 min-h-screen">
      {/* Report Header */}
      <div className="flex border-b-2 border-slate-200 pb-8 mb-8 items-center justify-between">
        <div>
          <h1 className="text-4xl font-black tracking-tighter text-blue-600">FLOWTRACK</h1>
          <p className="text-sm font-bold text-slate-400 mt-1 uppercase tracking-widest">Master Your Time • Study Performance Report</p>
        </div>
        <div className="text-right">
          <p className="text-sm font-bold text-slate-500 uppercase tracking-widest">Report Date</p>
          <p className="text-lg font-black text-slate-800">{format(new Date(), "MMMM dd, yyyy")}</p>
        </div>
      </div>

      {/* Summary Stats */}
      <div className="grid grid-cols-3 gap-6 mb-12">
        <div className="bg-slate-50 p-6 rounded-2xl border border-slate-100">
          <p className="text-xs font-bold text-slate-500 uppercase mb-1">Total Focused Hours</p>
          <p className="text-3xl font-black text-slate-900">{stats.totalHours}h</p>
        </div>
        <div className="bg-slate-50 p-6 rounded-2xl border border-slate-100">
          <p className="text-xs font-bold text-slate-500 uppercase mb-1">Total Sessions</p>
          <p className="text-3xl font-black text-slate-900">{stats.sessionCount}</p>
        </div>
        <div className="bg-slate-50 p-6 rounded-2xl border border-slate-100">
          <p className="text-xs font-bold text-slate-500 uppercase mb-1">Current Level & Rank</p>
          <p className="text-3xl font-black text-blue-600">Lv.{level} {rank}</p>
        </div>
      </div>

      {/* Subject Breakdown */}
      <div className="mb-12">
        <h2 className="text-xl font-black text-slate-800 mb-6 uppercase tracking-wider">Subject Analysis</h2>
        <div className="space-y-4">
          {subjects.map(subject => {
            const subSessions = sessions.filter(s => s.subjectId === subject.id);
            const subSeconds = subSessions.reduce((acc, s) => acc + s.actualSeconds, 0);
            const subHours = (subSeconds / 3600).toFixed(1);
            const percentage = stats.totalHours === "0.0" ? 0 : Math.round((parseFloat(subHours) / parseFloat(stats.totalHours)) * 100);

            return (
              <div key={subject.id} className="flex items-center gap-4">
                <div className="w-32 font-bold text-slate-700 truncate">{subject.name}</div>
                <div className="flex-1 h-3 bg-slate-100 rounded-full overflow-hidden">
                  <div 
                    className="h-full bg-blue-500 rounded-full" 
                    style={{ width: `${percentage}%` }}
                  />
                </div>
                <div className="w-20 text-right font-black text-slate-900">{subHours}h</div>
                <div className="w-12 text-right text-xs text-slate-400 font-bold">{percentage}%</div>
              </div>
            );
          })}
        </div>
      </div>

      {/* AI Performance Insights */}
      <div className="mb-12 bg-blue-50 p-8 rounded-3xl border border-blue-100">
        <h2 className="text-xl font-black text-blue-900 mb-6 uppercase tracking-wider flex items-center gap-2">
          <span>🧠</span> Performance AI Insights
        </h2>
        <div className="grid grid-cols-2 gap-8">
          {stats.insights.slice(0, 4).map((insight, idx) => (
            <div key={idx} className="bg-white/80 p-4 rounded-xl border border-blue-200/50">
              <h4 className="font-black text-blue-800 text-xs mb-1 uppercase">{insight.title}</h4>
              <p className="text-sm text-slate-700 leading-relaxed font-medium">
                {insight.description}
              </p>
            </div>
          ))}
        </div>
      </div>

      {/* Report Footer */}
      <div className="mt-auto border-t border-slate-200 pt-8 text-center bg-white">
        <p className="text-sm font-bold text-slate-400">
          This report was automatically generated by <span className="text-blue-600 font-black">FlowTrack App</span>. 
          Privacy First • Data Owned by User.
        </p>
      </div>

      {/* Verification Code Styles (Print Only) */}
      <style>{`
        @media print {
          body * { visibility: hidden; }
          #print-report, #print-report * { visibility: visible; }
          #print-report { position: absolute; left: 0; top: 0; width: 100%; }
          .no-print { display: none !important; }
        }
      `}</style>
    </div>
  );
}
